Pages/Auth.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Svper
{
    [AllowAnonymous]
    public class AuthModel : PageModel
    {
        public void OnGet() {

        }
        public async void OnGetSignoutAsync()
        {
            await HttpContext.SignOutAsync(User.FindFirst("tfp").Value);
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Svper
{
    public class ErrorModel : PageModel
    {
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Svper
{
    public class IndexModel : PageModel
    {       
        public void OnGet()
        {
        }
    }
}

Pages/home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Svper
{
    public class HomeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Auth.cshtml
@page "{handler?}"
@model AuthModel
<h3>Unauthenticated</h3>
<a asp-page="Index">Sign in again</a>

Pages/Index.cshtml
@page
@model IndexModel
<h1>Welcome to my amazing page</h1>
<a asp-page="./Home">See some detail</a>

Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head> 
    <title>Cool page</title>      
</head>
<body>    
   <a asp-page="./Auth" asp-page-handler="Signout">Sign Out</a>
    @RenderBody()  
</body>
</html>

Pages/home.cshtml
@page
@model HomeModel
<h2>Welcome @User.Identity.Name</h2>
<ul>
    @foreach (var claim in User.Claims)
    {
        <li>
            @claim.Type: @claim.Value
        </li>
    }
</ul>